title: Emerging Directions in Optical Computing and Information Processing Conference
preposition: at
#description: >-
description: >+
  June 26 and 27, 2025  
  (Virtual Conference)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://opticalcomputingconference.org/" # the base hostname & protocol for your site, e.g. https://example.com

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-include-cache

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Timezone
  tz: "+05:00"

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: OCC
      # img: ''
      url: 'https://opticalcomputingconference.org'
    breakpoint: md
    links:
      - name: Program
        relative_url: /program/
      - name: Registration
        relative_url: /registration/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: Registration
        relative_url: /registration/

  # Information boxes
  info_bars:
#    - title: Welcome to the Emerging Directions in Optical Computing and Information Processing Conference!
#      color: primary
#      main_only: true
#      text: >+
#        June 26 and 27, 2025
#        Virtual Conference
    - text: The conference website is being updated
      color: primary
      # pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Optical Computing
        color: dark
      - name: Photonic Integrated Circuits
        color: info
      - name: Quantum Information Processing
        color: success
      - name: Metamaterials
        color: warning

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 40.7350347213414, -73.82033094574881
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
